### PR TITLE
New options @key and @default

### PR DESCRIPTION
**Pull request by prepor**

### CODE REVIEW

**Comment by c-cube** [comment]
I really think you should become a maintainer :-). I'll give you commit rights unless you object.

**Comment by prepor** [comment]
Ok, thank you ;)

**Comment by c-cube** [comment]
Here you go :-)

**Comment by prepor** [comment]
I still don't have write access.

I've also added cconv support in my EDN parser https://github.com/prepor/ocaml-edn#ppx-generator

**Comment by prepor** [comment]
> I still don't have write access.

Op, sorry, now see invite

**Pull request merged**
