### PR TITLE
OCaml 4.03 compatibility

### PR DESCRIPTION
**Pull request by tizoc**
This works with 4.03 but not earlier versions, but I can make it work with older versions if is ok to add cppo as a dependency.

Doesn't add support for variants with inlined records (not entirely sure how that should work, would have to investigate more), it just handles that case by raising an error notifying the user that such case is not supported.

### CODE REVIEW

**Comment by c-cube** [comment]
Thanks for the contribution! cppo is a reasonable dependency and I think it should be worth it in this case. If you can implement it, please do (should only need to change the two auxiliary functions) and I will merge it!

**Comment by tizoc** [comment]
Yes, actually, I already had the cppo version of the file when I opened this pull request, but I still have to update the build files to handle that.

I will let you know once its done.

**Comment by tizoc** [comment]
I'm having a hard time making Oasis handle the .cppo.ml file (in part because of https://forge.ocamlcore.org/tracker/index.php?func=detail&aid=1659&group_id=54&atid=291 but even after downgrading to 0.4.6 I'm still having some issues).

I'm going to give it another try sometime during the weekend.

**Comment by tizoc** [comment]
Funny thing, a few minutes after I made the last comments I was able to make it work.

Still not ready for merging, I have to upgrade Oasis again and re-test to make sure if it is not working in 0.4.7, and if it doesn't flag it somehow (not today, but in the very near future).

Another detail is that Oasis doesn't recognize .cppo.ml files when searching for a module, so for `oasis setup` to work I had to temporarily create a dummy `ppx_deriving_cconv.ml` file which I later deleted.

**Comment by tizoc** [comment]
Ok, re-tested with Oasis 0.4.7 (it fails, because of the mentioned bug), and verified that it compiles fine with OCaml 4.02.

The current opam file doesn't mention Oasis, should I add that (with a `< "0.4.7"` constraint) or leave it as is? Being that the generated files are part of the repo I guess it is not necessary, and in that case, then no more commits are needed.

**Comment by c-cube** [comment]
Don't add the `oasis` dep, the generated files are checked in for  that precise reason. Thanks for the good work!

**Pull request merged**
